# Generated by Django 4.2 on 2023-05-25 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionsUsers',
            new_name='QuestionsUser',
        ),
    ]
