# Generated by Django 4.2 on 2023-05-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_questionsusers_questionsuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breed',
            options={'verbose_name_plural': 'Котячі породи'},
        ),
        migrations.AlterModelOptions(
            name='cat',
            options={'verbose_name_plural': 'Коти'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Пости користувача'},
        ),
        migrations.AlterModelOptions(
            name='postlanguage',
            options={'verbose_name_plural': 'Мови публікацій'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__username'], 'verbose_name_plural': 'Профілі'},
        ),
        migrations.AlterModelOptions(
            name='questionsuser',
            options={'verbose_name_plural': 'Питання користувачів'},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name_plural': 'Теми публікацій'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=4000),
        ),
    ]
