# Generated by Django 4.2 on 2023-05-26 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_breed_options_alter_cat_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': '-created_at', 'verbose_name_plural': 'Пости користувача'},
        ),
    ]
