# Generated by Django 4.2 on 2023-05-26 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'order_date', 'verbose_name_plural': 'Пости користувача'},
        ),
    ]
