# Generated by Django 4.2 on 2023-05-27 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
