# Generated by Django 4.2 on 2023-05-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_questionsuser_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsuser',
            name='theme',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
