# Generated by Django 4.2 on 2023-05-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_questionsuser_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsuser',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
