# Generated by Django 4.2 on 2023-05-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_questionsuser_answered'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='image',
            field=models.ImageField(blank=True, default='cat-profile-picture.gif', upload_to='profile_cats'),
        ),
    ]
