# Generated by Django 4.2 on 2023-06-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_cat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='image',
            field=models.ImageField(default='cat-profile-picture.gif', upload_to='profile_cats'),
        ),
    ]
